Blogs_site/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include

urlpatterns = [
    path('',include('blogs.urls', namespace='blogs')),
    path('users/', include('users.urls', namespace='users')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns

    # serve static and media files from development server
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogs/urls.py
from django.urls import path, re_path
from . import views

app_name = 'blogs'
urlpatterns = [
   # Home page
   path('', views.index, name='index'),
     # Page that show all the register blogs.
   path('blogs/', views.blogs, name='blogs'),
   # Page that show the lastest entries added to the site.
   path('lastest_entries/', views.lastest_entries, name='lastest_entries'),
   # Page to register a new blog.
   path('new_blog/', views.new_blog, name='new_blog'),
   # Page that show a specific blog by its id(primary key).
   path('blog/<int:pk>/', views.blog, name='blog'),
   # Page that confir delete of a Blog
   path('delete_blog/<int:pk>/', views.delete_blog, name="delete_blog"),
   # Page that allow users add a new entry to they blogs.
   path('new_entry/<int:pk>/', views.new_entry,name='new_entry'),
   # pag that show a specific view by it id(primary key).
   path('entry/<int:pk>/', views.entry, name='entry'),
   # Page that allows an user edit a blog entry.
   path('edit_entry/<int:pk>/', views.edit_entry, name='edit_entry'),
   # Page that confirm delete of an extiting entry
   path('delete_entry/<int:pk>/', views.delete_entry, name='delete_entry')
]

blogs/models.py
from django.db import models
from django.contrib.auth.models import User
from taggit.managers import TaggableManager

# Create your models here
    
class Blog(models.Model):
    '''A model that will store all the blogs.'''

    name = models.CharField(max_length=200)
    description = models.TextField()
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    date_added = models.DateTimeField(auto_now_add=True)
    tags = TaggableManager(blank=True)

    def __str__(self):
        return self.name


class Entry(models.Model):
    '''A model that will handle all the entries of our blogs.'''

    title = models.CharField(max_length=200)
    text = models.TextField()
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)
    img = models.ImageField(null=True, blank=True, upload_to='uploads/')
    tags =  TaggableManager(blank=True)
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta():
        verbose_name = 'entries'

    def __str__(self):
        return self.title

blogs/forms.py
from django import forms

from .models import Blog, Entry

class BlogForm(forms.ModelForm):
    class Meta:
        model = Blog
        fields = [
            'name',
            'description'
        ]


class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = [
            'title',
            'text',
            'img',
            'tags'
        ]

blogs/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User

from .models import Entry, Blog
from .forms import BlogForm, EntryForm


def index(request):
    """Home page"""
    return render(request, 'blogs/index.html')
    

def blogs(request):
    """Show the last 10 blogs available on the site."""
    try:
        blogs = Blog.objects.order_by('-date_added') [:10]
    except Blog.DoesNotExist:
        raise Http404('No blog has been found!')
    else:
        context = {'blogs': blogs}

    return render(request, 'blogs/blogs.html', context)


def lastest_entries(request):
    """ Show the lastest entries of the site."""
    try:
        entries = Entry.objects.order_by('-date_added') [:10] # the queryset only retrieve the last 10
    except Entry.DoesNotExist:
        raise Http404('No entry has been found!')  
    else:
        context = {'entries': entries}
    return render(request, 'blogs/lastest_entries.html', context)


def new_blog(request):
    # before testing comment out user authenticate 
    if not request.user.is_authenticated:
        return redirect('%s?next=%s' % ('/users/register/', request.path))
    else:
        if request.method != 'POST':
            form = BlogForm()
        else:
            form = BlogForm(request.POST)
            if form.is_valid():
                new_blog = form.save(commit=False)
                new_blog.owner =  request.user # for testing use User.objects.create(username='user', password='pass')
                new_blog.save()
                return redirect('blogs:blogs')

    context = {'form':form}
    return render(request, 'blogs/new_blog.html', context)


def blog(request, pk):
    """Show a single blog and its entries.
    take an blog_id or primaty key as positinal argument."""
    blog = get_object_or_404(Blog, pk=pk)
    
    name = blog.name
    description = blog.description
    entries = blog.entry_set.order_by("-date_added")

    context = {
        'blog':blog,
        'name': name,
        'description': description,
        'entries': entries,
    }

    return render(request, 'blogs/blog.html', context)

@login_required
def delete_blog(request, pk):
    # try to retreive blog or return 404 error
    obj = get_object_or_404(Blog, pk=pk)

    _check_blog_owner(obj, request)

    if request.method == 'POST':
        # delete object
        obj.delete()
        # after deleting redirect to blogs section
        return redirect('blogs:blogs')

    return render(request, 'blogs/delete_obj.html', {'object': obj})


@login_required
def new_entry(request, pk):
    '''View that takes an blog_id as parameter and return a form that allows user to create a new entry for a given blog.'''
    blog = get_object_or_404(Blog, pk=pk)

    _check_blog_owner(blog, request) # comment out before testing.

    if request.method != 'POST':
        form = EntryForm()
    else:
        form = EntryForm(request.POST, request.FILES)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.blog = blog
            new_entry.save()
            form.save_m2m()
            return redirect('blogs:blog', pk=pk)

    context = {'blog': blog, 'form': form}
    return render(request, 'blogs/new_entry.html', context)


def entry(request, pk):
    """Shows a single entry of an specific blog."""
    entry = get_object_or_404(Entry, pk=pk)

    title = entry.title
    text = entry.text
    blog = entry.blog
    img = entry.img
    tags = entry.tags.all()


    context = {
        'entry': entry,
        'title': title,
        'text': text,
        'blog': blog,
        'tags': tags,
        'img': img,
    }

    return render(request, 'blogs/entry.html', context)


@login_required
def edit_entry(request, pk):
    """Edit an existing entry. take a entry id as parameter and return a form with the data of an exiting entry."""
    entry = get_object_or_404(Entry, pk=pk)

    blog = entry.blog

    _check_blog_owner(blog, request) # comment out before testing

    if request.method != "POST":
        # Initial request; pre-fill form with the current entry.
        form = EntryForm(instance=entry)
    else:
        # POST data submitted; process data.
        form = EntryForm(request.POST, request.FILES, instance=entry)
        if form.is_valid():
            form.save()
            form.save_m2m()
            return redirect('blogs:blog', pk=pk)

    context = {"entry": entry, "blog": blog, "form": form}
    return render(request, "blogs/edit_entry.html", context)


@login_required
def delete_entry(request, pk):
    # try to retreive blog or return 404 error
    obj = get_object_or_404(Entry, pk=pk)

    _check_blog_owner(obj, request)
    
    if request.method == 'POST':
        # delete object
        obj.delete()
        # after deleting redirect to blogs section
        return redirect('blogs:blog', pk=obj.blog.id)

    return render(request, 'blogs/delete_obj.html', {'object': obj})


def _check_blog_owner(blog, request):
    if blog.owner != request.user:
        raise Http404

blogs/templates/blogs/blog.html
{% extends 'base.html' %}

{% block title %}{{blog.name}}{% endblock title %}

{% block content %}
  <div class="container my-3">
    <h2>{{ name|title }}</h2>
    <br />
    <p>{{ description }}</p>
  </div>

  <div class="container my-2">
    <p>Entries:</p>
    <ul class="list-group-flush">
      {% for entry in entries %}
      <li class="list-group-item my-2">
        <a href="{% url 'blogs:entry' entry.id %}" style="text-decoration: none; color:black;">{{ entry }}</a>
      </li>
      {% empty %}
      <li class="list-group-item my-2"><p>No entry has been added yet.</p></li>
      {% endfor %}
    </ul>

    {% if request.user == blog.owner %}
      <a href="{% url 'blogs:new_entry' blog.id %}" class="btn btn-outline-primary btn-sm">New entry</a>
      <a href="{% url 'blogs:delete_blog' blog.id %}" class="btn btn-outline-danger btn-sm">Delete blog</a>
    {% endif %}
  </div>
{% endblock content %}

blogs/templates/blogs/blogs.html
{% extends 'base.html' %}

{% block title %}Blogs{% endblock title %}

{% block content %}
{% load static %}
<section>

  <div class="container py-2">
    <h1>Blogs</h1>
    <ul class="list-group-flush">
      {% for blog in blogs %}
        <li class="list-group-item list-group-item-secondary my-3">
          <h3>{{ blog }}</h3>
          <p>{{ blog.description }}</p>
          <p>{{ blog.date_added|date:'D d, m, Y H'}}</p>
          <a href="{% url 'blogs:blog' blog.id %}" class="btn btn-info btn-sm">Read More</a>
        </li>
      {% empty %}
         <li class="list-group-item list-group-item-info"><p>No blog has been added yet.</p></li>
      {% endfor %}
    </ul>
  
    <a href="{% url 'blogs:new_blog'%}" class="btn btn-outline-primary">Add a new blog</a>
  </div>
  
</section>

{%endblock content%}

blogs/templates/blogs/delete_obj.html
{% extends 'base.html' %}

{% block title %}{{title}}{% endblock title %}

{% block content %}
<section>
  
    <div class="container text-center my-3" style="width: 700px; height: auto;">

        <div class="card bg-warning pt-3">

            <div class="card-block">

                <div class="card-title">
                    <h3>Do you want to delete {{object}}?</h3>
                </div>
                
                <div class="card-text pt-1">
                    <form method="POST">
                        <!-- Security token-->
                        {% csrf_token %}
                        <p>If you delete {{object}}, you will lose all of your progres.</p><br />
                        <button name='submit' class="btn btn-danger">Delete</button> 
                        <a href="{% url 'blogs:index'%}" class="btn btn-success">Cancel</a>
                    </form>
                </div>

            </div>

        </div>
    </div>
</section>

{% endblock content %}

blogs/templates/blogs/edit_entry.html
{% extends 'base.html' %}

{% block title %}Edit entry{% endblock title %}

{% block content %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/forms.css'%}">
<section>

  <div class="container">

    <h1>Edit entry: {{entry.title }}</h1>

    <form action="{% url 'blogs:edit_entry' entry.id %}" method='post' enctype="multipart/form-data">
      {% csrf_token %}
      {{ form.non_field_errors }}

      <div class="form-group">
        {{ form.title.errors }}
        {{ form.title.label_tag }}
        {{ form.title }}
      </div>
          
      <div class="form-group">
        {{ form.text.errors }}
        {{ form.text.label_tag }}
        {{ form.text }}
      </div>
    
      <div class="form-group">
        {{ form.img.errors }}
        {{ form.img.label_tag }}
        {{ form.img }}
      </div>
          
      <div class="form-group">
        {{ form.tags.errors }}
        {{ form.tags.label_tag }}
        {{ form.tags }}
      </div>

      <button name='submit' class="btn btn-outline-primary my-2">Submit</button>
    </form>

  </div>
  
</section>
  

{%endblock content%}

blogs/templates/blogs/entry.html
{% extends 'base.html' %}

{% block title %}{{title}}{% endblock title %}

{% block content %}
<section>
  
  <div class="container" style="margin:0 50px 0 50px;">

    <h2><a href='{% url "blogs:blog" blog.id %}' style="text-decoration: none; color:black;">{{ blog }}</a></h2>
      
    <h3>{{ title }}</h3>

    <div class="container">
      <div class="row">
        <div class="col-sm-4">
          <p>{{entry.date_added|date:'D d, m, Y'}}</p>
        </div>
        
        <div class="col-sm-1">
          <h6>Tags:</h6>
        </div>

        {% for tag in tags %}
          <div class="col-sm-1">
            <p>{{tag}}</p>
          </div>
        {% endfor %}
      </div>
    </div>

    {%if img %}
    <img src="{{img.url}}">
    {% endif %}

    <p>{{ text }}</p>

    {% if request.user == entry.blog.owner %}
      <a href="{% url 'blogs:edit_entry' entry.id %}" class="btn btn-outline-primary">Edit entry</a>
      <a href="{% url 'blogs:delete_entry' entry.id %}" class="btn btn-outline-danger">Delete Entry</a>
    {% endif %}
    
  </div>
</section>

{% endblock content %}

blogs/templates/blogs/index.html
{% extends 'base.html' %}
{% block title %}Welcome{% endblock title %}

{% block content %}

{% load static %}
<section>

  <div class="container pt-3 my-3">

    <div class="jumbotron bg-dark text-white">
      <h2>Hi, welcome to PyDev.com</h2>
      <p>
        This is <i>PyDev.com</i> here you can share all about your passion or anything you want. Here we love to read 
        crazy things and good stories!
      </p>
    </div>

  </div>

</section>

<!--<aside>
  <div class="container">
      <ul>
            <li>Latest:</li>
        {% for e in lts_entries %}
            <li>
              <a href='{% url "blogs:entry" e.id %}'>{{ e.title }}</a>
            </li>
        {% endfor %}
      </ul>
  </div>
</aside>-->
{%endblock content%}

blogs/templates/blogs/lastest_entries.html
{% extends 'base.html' %}

{% block title%}Latest Entries{% endblock title %}

{% block content %}
{% load static %}
<section>

  <div class="container my-2">
    <h2>Lastest</h2>

    <ul class="list-group-flush">
      {% for entry in entries %}
        <li class="list-group-item  list-group-item-secondary my-3">
          <h3>{{entry.title}}</h3>
          <p>{{entry.text}}</p>
          <p>{{entry.date_added|date:'D d, m, Y H'}}</p>
          <a href='{% url "blogs:entry" entry.id %}' class="btn btn-info btn-sm">Read More</a>
        </li>
      {% empty %}
        <li class="list-group-item list-group-item-info"><h4>No entry has been added yet.</h3></li>
      {% endfor %}
    </ul>
  </div>

</section>

{%endblock content%}

blogs/templates/blogs/new_blog.html
{% extends 'base.html' %}

{% block title %}new_blog{% endblock title %}

{% block content %}
{% load static %}
<link rel='stylesheet' type='text/css' href='{% static "css/forms.css"%}'/>

<section class="fields-set">

  <div class="container">

    <h1>Add a new blog:</h1>
    <form action="{% url 'blogs:new_blog' %}" method='post'>
      {% csrf_token %}
      {{ form.non_field_errors }}

      <div class="form-group">
        {{ form.name.errors }}
        {{ form.name.label_tag }}
        {{ form.name }}
      </div>
      
      <div class="form-group">
        {{ form.description.errors }}
        {{ form.description.label_tag }}
        {{ form.description }}
      </div>

      <button name='submit' class="btn btn-outline-primary">Add blog</button>
    </form>

  </div>
  
</section>

{%endblock content%}

blogs/templates/blogs/new_entry.html
{% extends 'base.html' %}

{% block title %}New entry{% endblock title %}

{% block content %}
{% load static %}
<link rel='stylesheet' type='text/css' href='{% static "css/forms.css"%}'/>
<section>

  <div class="container">

    <h1>{{blog.name}}</h1>
    <p>Add a new entry:</p>

    <form action="{% url 'blogs:new_entry' blog.id %}" method='post' enctype="multipart/form-data">
      {% csrf_token %}
      {{ form.non_field_errors }}

      <div class="form-group">
        {{ form.title.errors }}
        {{ form.title.label_tag }}
        {{ form.title }}
      </div>
      
      <div class="form-group">
        {{ form.text.errors }}
        {{ form.text.label_tag }}
        {{ form.text }}
      </div>
    
      <div class="form-group">
        {{ form.img.errors }}
        {{ form.img.label_tag }}
        {{ form.img }}
      </div>
      
      <div class="form-group">
        {{ form.tags.errors }}
        {{ form.tags.label_tag }}
        {{ form.tags }}
      </div>
          
      <button name='submit' class="btn btn-outline-primary">Add entry</button>
    </form>


  </div>
 
</section>

{%endblock content%}

blogs/templates/blogs/side_bar.html
{% extends 'base.html'%}
{% block side-bar %}
<h1>Lastest</h1>

  <ul>
      {% for e in lts_entries %}
        <li>
          <a href='{% url "blogs:entry" entry.id %}'>{{ e.title }}</a>
        </li>
      {% empty %}
        <li><h3>No entry has been added yet.</h3></li>
      {% endfor %}
  </ul>
{% endblock %}