Blogs_site/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include

urlpatterns = [
    path('',include('blogs.urls', namespace='blogs')),
    path('users/', include('users.urls', namespace='users')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns

    # serve static and media files from development server
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogs/urls.py
from django.urls import path, re_path
from . import views

app_name = 'blogs'
urlpatterns = [
   # Home page
   path('', views.index, name='index'),
     # Page that show all the register blogs.
   path('blogs/', views.blogs, name='blogs'),
   # Page that show the lastest entries added to the site.
   path('lastest_entries/', views.lastest_entries, name='lastest_entries'),
   # Page to register a new blog.
   path('new_blog/', views.new_blog, name='new_blog'),
   # Page that show a specific blog by its id(primary key).
   path('blog/<int:pk>/', views.blog, name='blog'),
   # Page that confir delete of a Blog
   path('delete_blog/<int:pk>/', views.delete_blog, name="delete_blog"),
   # Page that allow users add a new entry to they blogs.
   path('new_entry/<int:pk>/', views.new_entry,name='new_entry'),
   # pag that show a specific view by it id(primary key).
   path('entry/<int:pk>/', views.entry, name='entry'),
   # Page that allows an user edit a blog entry.
   path('edit_entry/<int:pk>/', views.edit_entry, name='edit_entry'),
   # Page that confirm delete of an extiting entry
   path('delete_entry/<int:pk>/', views.delete_entry, name='delete_entry')
]

users/urls.py
from django.urls import path
from django.conf.urls import include
from . import views


app_name = 'users'
urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('register/', views.register, name='register'),
    path('new_profile/<int:pk>/', views.new_profile, name='new_profile'),
    path('profile/<int:pk>/', views.profile, name='profile'),
    path('edit_profile/<int:pk>/', views.edit_profile, name='edit_profile'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import User

class UserProfile(models.Model):
    '''A extension of the defaul User model. It will store detailed data about an user.'''
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
    name = models.CharField(max_length=100, blank=True, null=True)
    last_name = models.CharField(max_length=100, blank=True, null=True)
    description = models.TextField()
    profile_img = models.ImageField(upload_to='profile_img/', blank=True)
    email = models.EmailField(blank=True)
    twitter = models.URLField(blank=True)

# Create your models here.

users/forms.py
from django import forms
from users.models import UserProfile

class UserProfileForm(forms.ModelForm):
    
    class Meta:
        model = UserProfile
        fields = [
            'name',
            'last_name',
            'description',
            'profile_img',
            'email',
            'twitter'
        ]

users/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from users.forms import UserProfileForm
from users.models import UserProfile

# Create your views here.
def dashboard(request):
    return render(request, 'users/dashboard.html')


def register(request):
    '''Register a new user'''
    if request.method != 'POST':
        #display blank registration form.
        form = UserCreationForm()
    else:
        # process completed.
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            # Login and then redirect  to the home page.
            login(request, new_user)
            return redirect('users:dashboard')

    # display a blank or invalid form.
    context = {'form': form}
    return render(request, 'registration/register.html', context)

@login_required
def profile(request, pk):
    #user_profile = get_object_or_404(UserProfile, pk=pk)
    try:
        profile = User.profile.objects.get(pk=pk)
    except:
        return redirect('users:new_profile', pk=pk)


    full_name = f'{profile.name} {profile.last_name}'
    user_name = request.user.username
    description = profile.description
    email = profile.email
    twitter = rofile.twitter
    profile_img = profile.profile_img

    context = {
        'full_name': full_name,
        'user_name': user_name,
        'description': description,
        'email': email,
        'twitter': twitter,
        'profile_img': profile_img,
    }

    return render(request, 'users/profile.html', context)


@login_required
def new_profile(request, pk):
    '''Create a new user profile.'''
    user = User.objects.get(pk=pk)

    form = UserProfileForm(request.POST, request.FILES)

    if form.is_valid():
        new_profile = form.save(commit=False)
        new_profile.user = user
        new_profile.save()
        return redirect('users:profile', pk=pk)

    context = {'form': form}
    return render(request, 'users/new_profile.html', context)
    
@login_required
def edit_profile(request, pk):
    """Edit an existing profile."""
    profile = get_object_or_404(UserProfile, pk=pk)

    user = profile.user

    if request.method != "POST":
        # Initial request; pre-fill form with the current entry.
        form = UserProfileForm(instance=profile)
    else:
        # POST data submitted; process data.
        form = UserProfileForm(request.POST, request.FILES, instance=profile)
        if form.is_valid():
            form.save()
            return redirect('users:profile', pk=pk)

    context = {"profile": profile, "user": user, "form": form}
    return render(request, "users/edit_profile.html", context)

users/templates/users/dashboard.html
{% extends 'base.html' %}

{% block title %} User dashboard {% endblock title %}

{% block content %}

<h2>Hello, {{user.username|default:'Guesst'}}!</h2>

<div>
    {% if user.is_authenticated %}
      <a href="{% url 'users:logout'%}">Logout</a>
      <a href="{% url 'users:password_change'%}">Change Password</a>
    {% else %}
      <a href="{% url 'users:login'%}">Login</a>
    {% endif %}
</div>
{% endblock content %}

users/templates/users/edit_profile.html
{% extends 'base.html'%}

{% block title%}Edit User Profile{% endblock title %}

{% block content %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/forms.css'%}">

<section>

  <div class="container">

    <h1>Edit</h1>

    <form action="{% url 'users:edit_profile' user.id %}" method='post' enctype="multipart/form-data">
      {% csrf_token %}
      {{ form.non_field_errors }}

      <div class="form-group">
        {{ form.name.errors }}
        {{ form.name.label_tag }}
        {{ form.name }}
      </div>

      <div class="form-group">
        {{ form.last_name.errors }}
        {{ form.last_name.label_tag }}
        {{ form.last_name }}
      </div>
      
      <div class="form-group">
        {{ form.description.errors }}
        {{ form.description.label_tag }}
        {{ form.description }}
      </div>

      <div class="form-group">
        {{ form.profile_img.errors }}
        {{ form.profile_img.label_tag }}
        {{ form.profile_img }}
      </div>

      <div class="form-group">
        {{ form.email.errors }}
        {{ form.email.label_tag }}
        {{ form.email }}
      </div>

      <div class="form-group">
        {{ form.twitter.errors }}
        {{ form.twitter.label_tag }}
        {{ form.twitter }}
      </div>

      <button name='submit' class="btn btn-outline-primary">Update</button>
    </form>
  </div>
    
</section>
{% endblock content %}

users/templates/users/new_profile.html
{% extends 'base.html'%}

{% block title%}New User Profile{% endblock title %}

{% block content %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/forms.css'%}">

<section id="user-profile">

  <div class="container">

    <form action="{% url 'users:new_profile' user.id %}" method='post' enctype="multipart/form-data">
      {% csrf_token %}
      {{ form.non_field_errors }}

      <div class="form-group">
        {{ form.name.errors }}
        {{ form.name.label_tag }}
        {{ form.name }}
      </div>

      <div class="form-group">
        {{ form.last_name.errors }}
        {{ form.last_name.label_tag }}
        {{ form.last_name }}
      </div>
      
      <div class="form-group">
        {{ form.description.errors }}
        {{ form.description.label_tag }}
        {{ form.description }}
      </div>

      <div class="form-group">
        {{ form.profile_img.errors }}
        {{ form.profile_img.label_tag }}
        {{ form.profile_img }}
      </div>

      <div class="form-group">
        {{ form.email.errors }}
        {{ form.email.label_tag }}
        {{ form.email }}
      </div>

      <div class="form-group">
        {{ form.twitter.errors }}
        {{ form.twitter.label_tag }}
        {{ form.twitter }}
      </div>

      <button name='submit' class="btn btn-outline-primary">Submit</button>
    </form>
  </div>
    
</section>
{% endblock content %}

users/templates/users/profile.html
{% extends 'base.html' %}
{% block title %} Profile {% endblock title %}
{% load static %}
{% block content %}

<section style="text-align: center;">

  <div class="container my-3" style="max-width: 650px;min-width: 300px; height: auto;">

    <div class="card">

      <div class="card-hearder">
        <h2>Profile</h2>
      </div>

      {% if not user.profile.profile_img %}
        <img src="{% static 'img/profile-img.png'%}" class="card-img-top" style="width:auto; height:200px;">
      {% else %}
        <img src="{{profile_img.url}}" class="card-img-top" style="width:auto; height:200px;" >
      {% endif %}

      <div class="card-body">
        <h3 class="card-title">{{ full_name }}</h3>
        <p class="card-text">User Name:         {{user_name }}</p>
        <p class="card-text"></p>Description:   {{  description }}</p>
        <p class="card-text">Email:             {{ email }}</p>
        <p class="card-text">Twitter:           {{ twitter }}</p>
      </div>

      <div class="card-footer">
        <a href="{% url 'users:edit_profile' user.profile.id %}" class="btn btn-outline-success">Edit Profile</a>
      </div>
    </div>

  </div>
    
</section>
{% endblock content %}