Blogs_site/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include

urlpatterns = [
    path('',include('blogs.urls', namespace='blogs')),
    path('users/', include('users.urls', namespace='users')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns

    # serve static and media files from development server
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogs/urls.py
from django.urls import path, re_path
from . import views

app_name = 'blogs'
urlpatterns = [
   # Home page
   path('', views.index, name='index'),
     # Page that show all the register blogs.
   path('blogs/', views.blogs, name='blogs'),
   # Page that show the lastest entries added to the site.
   path('lastest_entries/', views.lastest_entries, name='lastest_entries'),
   # Page to register a new blog.
   path('new_blog/', views.new_blog, name='new_blog'),
   # Page that show a specific blog by its id(primary key).
   path('blog/<int:pk>/', views.blog, name='blog'),
   # Page that confir delete of a Blog
   path('delete_blog/<int:pk>/', views.delete_blog, name="delete_blog"),
   # Page that allow users add a new entry to they blogs.
   path('new_entry/<int:pk>/', views.new_entry,name='new_entry'),
   # pag that show a specific view by it id(primary key).
   path('entry/<int:pk>/', views.entry, name='entry'),
   # Page that allows an user edit a blog entry.
   path('edit_entry/<int:pk>/', views.edit_entry, name='edit_entry'),
   # Page that confirm delete of an extiting entry
   path('delete_entry/<int:pk>/', views.delete_entry, name='delete_entry')
]

users/urls.py
from django.urls import path
from django.conf.urls import include
from . import views


app_name = 'users'
urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('register/', views.register, name='register'),
    path('new_profile/<int:pk>/', views.new_profile, name='new_profile'),
    path('profile/<int:pk>/', views.profile, name='profile'),
    path('edit_profile/<int:pk>/', views.edit_profile, name='edit_profile'),
]

templates/base.html
<!DOCTYPE html>
<html lang='en'>
    <head>
        <meta charset='utf-8'>
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <title>{% block title %}Code Journey{% endblock title %}</title>
        {% load static %}
        <!--bootstrap-->
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" 
        integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    </head>

    <body>

      <nav class="navbar navbar-expand-sm navbar-light" style="background-color:#5aa19e">
        <!-- Brand -->
        <a class="navbar-brand" href="{% url 'blogs:index'%}"><span style="color: #ffffff; font-weight: bold;">Py</span>Dev</a>

        <!-- Toggler Button -->
        <button class="navbar-toggler" type="button" data-toggle="collapse"
              data-target="#navbarCollapse">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarCollapse">
          <!-- Navbar Links -->

          <!-- normal user options -->
          <ul class="navbar-nav">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'blogs:index'%}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'blogs:blogs'%}">Blogs</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'blogs:lastest_entries'%}">Lastest</a>
            </li>
         </ul>
         <!-- normal user options -->

         <!-- Authenticated user option -->
          <ul class="navbar-nav ml-auto">
            {% if user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'users:logout'%}">Logout</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'users:profile' user.id %}">
                {% if user.profile %}
                  <img class="avatar" src="{{user.profile.profile_img.url}}" atl="avatar" style="width: 30px;
                  height: 30px;
                  border-radius: 45%;"/>
                {% else %}
                  <img class="avatar" src="{% static 'images/profile-image.png' %}" atl="avatar" style="width: 30px;
                  height: 30px;
                  border-radius: 45%"/>
                {% endif %}
                </a>
              </li>
            {% else %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'users:login'%}">Login</a>
              </li>
              <li class="nav-item"> 
                <a class="nav-link" href="{% url 'users:register'%}">Singin</a>
              </li>
            {% endif %}
          </ul>
          <!-- Authenticated user option -->
        </div>
      </nav>

      <article>
          {% block content %} 

          {% endblock content %}
      </article>

      <footer class="page-footer font-small my-2" style="background-color: #36615f;">
        <!-- Copyright -->
        <div class="footer-copyright text-center py-3">&copy2020 Copyright:
          <a href="{% url 'blogs:index'%}" class="text-light">PyDev.com</a>
        </div>
        <!-- Copytight -->
      </footer>
      <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" 
      integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" 
      integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
    </body>

</html>